//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RainbowDataAnalyzer {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RainbowDataAnalyzer.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Sitecore ID should refer to a template field in serialized Rainbow data.
        /// </summary>
        internal static string FieldIdsAnalyzerDescription {
            get {
                return ResourceManager.GetString("FieldIdsAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This ID refers to a Sitecore item which is not a field (checked in Rainbow data).
        /// </summary>
        internal static string FieldIdsAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("FieldIdsAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sitecore ID is not a template field in Rainbow (Unicorn) data.
        /// </summary>
        internal static string FieldIdsAnalyzerTitle {
            get {
                return ResourceManager.GetString("FieldIdsAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field name should refer to a valid template field in serialized Rainbow data.
        /// </summary>
        internal static string FieldPathsAnalyzerDescription {
            get {
                return ResourceManager.GetString("FieldPathsAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid template field with name &apos;{0}&apos; could not be found.
        /// </summary>
        internal static string FieldPathsAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("FieldPathsAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sitecore field name could not be found in Rainbow (Unicorn) data.
        /// </summary>
        internal static string FieldPathsAnalyzerTitle {
            get {
                return ResourceManager.GetString("FieldPathsAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sitecore IDs should be available in serialized Rainbow (Unicorn) data.
        /// </summary>
        internal static string IdsAnalyzerDescription {
            get {
                return ResourceManager.GetString("IdsAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An item with id &apos;{0}&apos; could not be found.
        /// </summary>
        internal static string IdsAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("IdsAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sitecore ID could not be found in Rainbow (Unicorn) data.
        /// </summary>
        internal static string IdsAnalyzerTitle {
            get {
                return ResourceManager.GetString("IdsAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sitecore paths should be available in serialized Rainbow (Unicorn) data.
        /// </summary>
        internal static string PathsAnalyzerDescription {
            get {
                return ResourceManager.GetString("PathsAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An item with path &apos;{0}&apos; could not be found.
        /// </summary>
        internal static string PathsAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("PathsAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sitecore path could not be found in Rainbow (Unicorn) data.
        /// </summary>
        internal static string PathsAnalyzerTitle {
            get {
                return ResourceManager.GetString("PathsAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field that the ID refers to should be on one of the indicated templates.
        /// </summary>
        internal static string TemplateFieldIdsAnalyzerDescription {
            get {
                return ResourceManager.GetString("TemplateFieldIdsAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &apos;{0}&apos; is not on the template &apos;{1}&apos; or on any of its base templates.
        /// </summary>
        internal static string TemplateFieldIdsAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("TemplateFieldIdsAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field ID is not on any of the indicated templates in Rainbow (Unicorn) data.
        /// </summary>
        internal static string TemplateFieldIdsAnalyzerTitle {
            get {
                return ResourceManager.GetString("TemplateFieldIdsAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field that the name refers to should be on one of the indicated templates.
        /// </summary>
        internal static string TemplateFieldPathsAnalyzerDescription {
            get {
                return ResourceManager.GetString("TemplateFieldPathsAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &apos;{0}&apos; is not on the template &apos;{1}&apos; or on any of its base templates.
        /// </summary>
        internal static string TemplateFieldPathsAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("TemplateFieldPathsAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field is not on any of the indicated templates in Rainbow (Unicorn) data.
        /// </summary>
        internal static string TemplateFieldPathsAnalyzerTitle {
            get {
                return ResourceManager.GetString("TemplateFieldPathsAnalyzerTitle", resourceCulture);
            }
        }
    }
}
